### ISSUE TITLE
Have several instances of the interpreter

### ISSUE THREAD

**Issue by cdupont** [cdupont/Nomyx#102]
It seem necessary to have on instance of the interpreter per game, and one for the library.

**Comment by cdupont** [comment]
The ideal case would be to initialize an interpreter each time it is needed (each time we need to interpret a rule code) but this is long.
Measured time for startup of the interpreter is 4.5 sec.

Different interpreter for each game seem necessary: otherwise the declarations on one game can pollute another.
An interpreter for the library different from the games is necessary because in the library the declarations can change while in the games they are fixed.

When a rule's declarations are modified in the library, the corresponding interpreter should be reset. Then the declarations are loaded, together with all the other declarations. The rule expression is also checked.

**Comment by cdupont** [comment]
Benchmark of the interpreter startup:
- runIn: 1s
- loadModules: 1s
- setImportsQ: 1s

From reset to load complete, 2.2 seconds elapsed.
Is it reasonable to reset the interpreter for each rule interpret?

**Comment by cdupont** [comment]
Size in memory is very big:
pidof Nomyx | xargs ps -o rss,sz,vsz
  RSS    SZ    VSZ
620Mo 232Mo 928Mo

**Comment by cdupont** [comment]
Nomyx: This version of GHC is not thread-safe,can't safely run two instances of the interpreter simultaneously

**Comment by cdupont** [comment]
GHC trac about having multiple instances of the linker:
https://ghc.haskell.org/trac/ghc/ticket/3372
https://ghc.haskell.org/trac/ghc/wiki/MultipleLinkerInstances

Apparently there was an attempt but it was reverted:
https://mail.haskell.org/pipermail/ghc-commits/2014-December/009874.html

**Comment by cdupont** [comment]
Reply from Simon Marlow:

"Most of GHC is thread-safe, and it supports parallel compilation (ghc -j).  However, you cannot have multiple independent GHC API sessions running in different threads, because the runtime linker is global state.  I believe if you're not actually running code and just using the GHC API for compiling and inspecting code, then it should be possible to use multiple threads."

**Comment by cdupont** [comment]
Solution seems to be to restart the instance for each rule interpret. That simplifies much because we can remove the server handle and there is no problem of modules.

**Comment by cdupont** [comment]
Interpreting rules feels instant now. Closing

**Comment by habemus-papadum** [comment]
@cdupont Hi -- thanks for this record.  Could you explain what exactly was the resolution i.e. "restart the instance" -- from your initial posts it seems like this was initially too slow ~4s, but it seems like you came across a final solution that was workable -- somewhere I'm missing what exactly was done...  thanks

**Comment by cdupont** [comment]
Hi habemus-papadum,
are you trying to use hint?
The only solution I found for repeated evaluations in hint is to reset the interpreter for each evaluations.
Everything is reloaded: modules, GHC options etc.
See https://github.com/nomyx/nomyx-core/blob/6a27846a04a5a6d5f02b2735b2f6d3dd3e6cd0e1/src/Nomyx/Core/Engine/Interpret.hs#L77

However I initialize the engine a first time at program start: https://github.com/nomyx/nomyx-core/blob/6a27846a04a5a6d5f02b2735b2f6d3dd3e6cd0e1/src/Nomyx/Core/Engine/Interpret.hs#L38

After this first initialization, the next resets should be faster.

**Comment by habemus-papadum** [comment]
yes -- I am using hint and saw the "This version of GHC is not thread-safe,can't safely run two instances of the interpreter simultaneously" message which lead me here, but then I realized some of the other things being discussed were relevant as well.  

Thanks very much, this clarifies how you split things to manage the runtime overhead.   Cheers,  nehal

**Comment by gelisam** [comment]
> Apparently there was an attempt but it was reverted:
> https://mail.haskell.org/pipermail/ghc-commits/2014-December/009874.html

Btw that was only a temporary setback, [the revert was reverted](https://github.com/ghc/ghc/commit/55a2a0b4893486e5dde151620d7f46e8035d2af5) soon afterwards and the GHC linker has been thread-safe [since ghc 7.10.1](https://downloads.haskell.org/~ghc/7.10.1/docs/html/users_guide/release-7-10-1.html#idp5860656).

> Reply from Simon Marlow:
> 
> "Most of GHC is thread-safe, and it supports parallel compilation (ghc -j). However, you cannot have multiple independent GHC API sessions running in different threads, because the runtime linker is global state. I believe if you're not actually running code and just using the GHC API for compiling and inspecting code, then it should be possible to use multiple threads."

@cdupont May I ask where you found that quote? I suspect, but would like to confirm, that this is a quote from 2014 or earlier, since the runtime linker was no longer global in 2015.

> yes -- I am using hint and saw the "This version of GHC is not thread-safe,can't safely run two instances of the interpreter simultaneously" message which lead me here

On behalf of the hint team, please accept our apologies; this message was added when the GHC API wasn't thread-safe, but we failed to remove the message when it became thread-safe in 2014. [We will remove it now](https://github.com/mvdan/hint/issues/68#issuecomment-419088813).

**Comment by cdupont** [comment]
@gelisam S. Marlow send it to me by email on Septembre 2015.

**Comment by gelisam** [comment]
Uh oh. That throws a wrench into my understanding of the situation. Could it be that Simon fixed the problem in 2014, but later the problem reappeared, so that as of 2015 the problem still existed? Or perhaps the problem he fixed in 2014 is a different problem?
