### ISSUE TITLE
Url generation port on proxy

### ISSUE THREAD

**Issue by ferry-** [cdupont/Nomyx#114]
I'm trying to host the game on my server, binding the nomyx server itself to localhost on its own unprivileged port, while exposing it to the internet via an nginx virtual host (as a subdomain) on port 80. The issue is that after loading the main page, all generated URLs include the internal port number of the nomyx server itself.
Would it be possible to stop using the "port" argument to generate URLs and instead include the public port in the "host" argument? 
For example,
Nomyx --port=8021 --host="nomyx.domain:8080", would bind the server to localhost:8021 and generate URLs as nomyx.domain:8080/stuff

**Comment by cdupont** [comment]
Hi ferry- 
For what you want to do, could you use nginx rewrite rules?
https://www.nginx.com/blog/creating-nginx-rewrite-rules/

**Comment by ferry-** [comment]
The problem is the port. The generated URLs include the internal port of the Nomyx server, which I'm trying to hide from the remote client. Nginx does not bind on that port (both it and the Nomyx server couldn't, at the same time anyway)

**Comment by cdupont** [comment]
The problem is that Nomyx is generating absolute URLs for its internal links, such as

    http://localhost:8000/Nomyx/menu/details/Game

Where it should be relative URLs:

    /Nomyx/menu/details/Game

I will check how to correct that.
In the mean time, it seems that we can rewrite those URLs using a nginx module:
http://nginx.org/en/docs/http/ngx_http_sub_module.html#sub_filter

However it seems that this module is not included by default and need to be compiled :(

**Comment by ferry-** [comment]
Thanks for looking into this.
On  `Nomyx/Nomyx-Web/src/Nomyx/Web/MainPage.hs:235`, I think the root path is being created, with a port specified. Would changing that port work change the url generation? I'd test it myself but I wasn't able to build the project.

**Comment by cdupont** [comment]
It's pushed in branch Library.
I tested with nginx with the configuration:

    server {
        listen 1235 default;
        location / {
                proxy_pass http://lcdupont:8000/;
        }
    }
