### ISSUE TITLE
Please update supported versions of your depencies

### ISSUE THREAD

**Issue by peti** [cdupont/Nomyx#85]
According to http://packdeps.haskellers.com/feed?needle=Nomyx-Core, many of the dependencies have newer versions. We have updated those packages in NixOS a while ago, and now we can no longer compile this package as a result: http://hydra.cryp.to/build/621867/nixlog/1/raw.

**Comment by cdupont** [comment]
Hi Peter,
thanks for letting me know!
Just to know, are you trying to compile Nomyx for NixOS? Is it part of a
sanity check?
Cheers,
Corentin

**Comment by peti** [comment]
NixOS packages (almost) all of Hackage. As a part of that effort, our CI environment reported an error for this package.

**Comment by peti** [comment]
I'll remove Nomyx from the Nixpkgs distribution for the time being as we cannot build it. I'll re-add it again once this issue is closed.

**Comment by cdupont** [comment]
Hi Peter, should I update all the dependencies of Nomyx that have new
versions, or only hscolor that seems to break your build?
How can I test myself that it will work for Nixpkgs?

**Comment by peti** [comment]
Well, personally I believe it would be great to update all dependencies to include the respective latest version. IMHO, most builds will succeed fine once the upper bound has updated in the Cabal file. The issue with hscolour is the most important one, obviously. If that issue were fixed, then we could probably build Nomyx in Nix after running [jailbreak-cabal](http://hackage.haskell.org/package/jailbreak-cabal) to take care of the other restrictions.

Anyway, you can test those builds by installing Nix on your system. There are packages available for many Linux variants and for Darwin: http://nixos.org/nix/download.html. It's also possible to run NixOS inside of a virtual machine, i.e. using qemu, docker, etc. Setting that up is probably a greater effort, though.

**Comment by cdupont** [comment]
I fixed the problem with the last version of hscolour. Now it compile with -any on all dependencies.
However should I really put -any in the cabal? That doesn't seem good: Nomyx is an executable, so it doesn't hurt to make it depend on strict versions of the libraries.
Furthermore by setting the last version of all the libraries it won't compile, because some of my dependencies has not been updated (package time-recurrence relies on time=1.4.*, for example).

So what is the best strategy? I'm also wondering why Nix needs to have all packages updated. The standard procedure for Haskell is now to use sandboxes...

**Comment by peti** [comment]
> I fixed the problem with the last version of hscolour. Now it compile with -any on all dependencies.

Very good, thank you. Once that new version shows up on Hackage, NixOS will pick it up.


> However should I really put -any in the cabal?

Personally, I hardly ever specy an upper limit. It's a matter of taste, though. Most people tend to restrict updates to ones that say within the same major release, i.e. updating foo 1.1 to 1.2 is fine, but updating to foo 2.x is not.


> Nomyx is an executable, so it doesn't hurt to make it depend on strict versions of the libraries.

Well, it certainly hurts distributors like us. That's why we're having that conversation, no?


> Furthermore by setting the last version of all the libraries it won't compile, because some of my dependencies has not been updated (package time-recurrence relies on time=1.4.*, for example).

What I do on these occasions is to open a ticket with the library author and ask them to please update their Cabal files to allow the latest versions. GHC 7.10.x is going to be released soon, and it ships time 1.5.x. Libraries that don't support that version cannot be compiled with compiler then, which isn't a particularly nice situation.


> So what is the best strategy?

If you use a large portion of a libraries API, then restrict it's version to the same major release. If you use only a handful of simple functions that are unlikely to change, then place no restriction on the library version at all.


> I'm also wondering why Nix needs to have all packages updated. The standard procedure for Haskell is now to use sandboxes...

What do you mean by "standard procedure"? Is there a document on haskell.org somewhere that states that sandboxes must/should be used?

As far as I know, sandboxes are a kludge that was introduced into cabal-install to work around severe limitations in ghc-pkg, i.e. it's inability to install several versions/variants of the same library. That limitation has been lifted in GHC 7.8.x, IMHO, which makes sandboxes obsolete. Note that Cabal has never supported sandboxes in the first place; this is a feature provided only by the cabal-install utility (which we don't use in NixOS).

**Comment by cdupont** [comment]
So, the best is to set lower bounds but no upper bounds?

**Comment by cdupont** [comment]
I uploaded a new version of Nomyx in Haskage with bumped version of hscolour.
This version should compile with -any.
However I didn't updated upper bounds yet, since I'm waiting for other packages to update.
Tell me if it's OK for NixOS :)

**Comment by peti** [comment]
Very nice -- thank you very much for your efforts: http://hydra.cryp.to/eval/305491#tabs-new
